[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SparseArrayKit = "a9a3c162-d163-4c15-8926-b8794fbefed2"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
